// Bakes the 100 generated levels (5 tiers x 20) into src/levels_gen.js.
// node tools/gen_levels.js
const fs=require('fs'),path=require('path');
const E=require('../src/engine.js');const {makeGen}=require('../src/gen.js');
const G=makeGen(E);
const out=[],names=new Set(),count={};
const score=lv=>lv.pieces.filter(p=>!p.fixed).length*3+lv.pieces.filter(p=>p.t==='goal').length*2+lv.pieces.filter(p=>p.t==='wall').length;
for(let tier=1;tier<=5;tier++){
  const fams=G.familiesFor(tier),want=[];
  // glass balls, lenses and black holes are a must; every other family appears at least once
  const MIN={orb:3,zoom:1,spread:1,focus:1};
  if(tier>=2)MIN.hole=tier===2?2:tier===3?2:3;
  for(const f in MIN)for(let k=0;k<MIN[f];k++)want.push(f);
  for(const f of fams)if(!want.includes(f))want.push(f);
  for(let k=0;want.length<20;k++)want.push(fams[(k*5+tier)%fams.length]);
  want.length=20;
  const lvs=[];
  want.forEach((fam,k)=>{
    for(let a=0;a<400;a++){
      const seed=tier*10000+k*131+a;
      const lv=G.make(seed,tier,fam);
      if(!lv)continue;
      if(names.has(lv.name))continue;
      names.add(lv.name);lv.seed=seed;lvs.push(lv);break;
    }
  });
  if(lvs.length!==20){console.log('tier',tier,'short; wanted',want.join(','),'got',lvs.map(l=>l.family).join(','));process.exit(1)}
  lvs.sort((a,b)=>score(a)-score(b));
  if(tier===1){const i=lvs.findIndex(l=>l.family==='orb');lvs.unshift(lvs.splice(i,1)[0])}
  for(const lv of lvs){count[lv.family]=(count[lv.family]||0)+1;out.push(lv)}
}
const strip=lv=>({name:lv.name,hint:lv.hint,pieces:lv.pieces,sol:lv.sol,...(lv.pol?{pol:1}:{}),...(lv.coh?{coh:1}:{})});
const body=out.map(lv=>'/*'+lv.family+' '+lv.seed+'*/'+JSON.stringify(strip(lv))).join(',\n');
fs.writeFileSync(path.join(__dirname,'../src/levels_gen.js'),
'// Generated by tools/gen_levels.js. Do not edit by hand.\nconst GEN_LEVELS=[\n'+body+'\n];\nif(typeof module!==\'undefined\')module.exports={GEN_LEVELS};\n');
console.log(out.length,'levels',JSON.stringify(count));
